[build]
target = "rustup-riscv64gc-unknown-uefi/riscv64gc-unknown-uefi.json"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-uefi]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-nostdlib",
    "-C", "link-arg=-Tlinker.ld",
]
