[build]
target = "riscv64gc-unknown-none-elf"

[unstable]
build-std = ["core", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.riscv64gc-unknown-uefi]
linker = "rust-lld"
rustflags = [
    "-C", "link-arg=-nostdlib",
]
